/*
 * ASCII Pitfall!
 * Copyright (C) 2008 Michael Birken
 * 
 * This file is part of ASCII Pitfall!.
 *
 * ASCII Pitfall! is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published 
 * by the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * ASCII Pitfall! is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AsciiPitfall {
  partial class Program {
    public Sprite titleSprite = new Sprite(new String[] {
      "                                X                                                                  ",
      "                               X X      XXXXX    XXXXX  XXXXXXX  XXXXXXX                           ",
      "                              X   X    X        X          X        X                              ",
      "                             XXXXXXX    XXXXX   X          X        X                              ",
      "                            X       X        X  X          X        X                              ",
      "                           X         X  XXXXX    XXXXX  XXXXXXX  XXXXXXX                           ",
      "                                                                                                   ",
      "XXXXXXXXXXXX                                                                                   XXXX",
      "XXXXXXXXXXXXXX  XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX    XXXX         XXXX          XXXX          XXXX",
      "XXXX       XXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX   XXXXXX        XXXX          XXXX          XXXX",
      "XXXX       XXXX XXXX      XXXX      XXXX            XXXXXXXX       XXXX          XXXX          XXXX", 
      "XXXXXXXXXXXXXX  XXXX      XXXX      XXXXXXXXXXXX   XXXX  XXXX      XXXX          XXXX          XXXX",
      "XXXXXXXXXXXX    XXXX      XXXX      XXXXXXXXXXXX  XXXX    XXXX     XXXX          XXXX          XXXX",
      "XXXX            XXXX      XXXX      XXXX         XXXXXXXXXXXXXX    XXXX          XXXX          XXXX",
      "XXXX            XXXX      XXXX      XXXX        XXXXXXXXXXXXXXXX   XXXX          XXXX              ",
      "XXXX            XXXX      XXXX      XXXX       XXXX          XXXX  XXXXXXXXXXXXX XXXXXXXXXXXXX XXXX",
      "XXXX            XXXX      XXXX      XXXX      XXXX            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXX",
    }, 
      new char[] { 'X' },
      new ConsoleColor[] { ConsoleColor.White }
    );
    public Sprite ringSprite = new Sprite(new String[] {
      "                ",
      "                ",
      "                ",
      "    XXXXXX      ",
      "  XXXXXXXXXX    ",
      "    XXXXXX      ",
      "      XX        ",
      "    XXXXXX      ",
      "  XXXX  XXXX    ",
      "  XX      XX    ",
      "  XX      XX    ",
      "  XX      XX    ",
      "  XXXX  XXXX    ",
      "    XXXXXX      ",
      "                ",
      "                ",
    }, new ConsoleColor[] {
      ConsoleColor.Black,
      ConsoleColor.Black,
      ConsoleColor.Black,
      ConsoleColor.White,
      ConsoleColor.White,
      ConsoleColor.White,
      ConsoleColor.Yellow,
      ConsoleColor.Yellow,
      ConsoleColor.Yellow,
      ConsoleColor.Yellow,
      ConsoleColor.Yellow,
      ConsoleColor.Yellow,
      ConsoleColor.Yellow,
      ConsoleColor.Yellow,
      ConsoleColor.Black,
      ConsoleColor.Black,
    });
    public Sprite[] goldSprites = new Sprite[] {
      new Sprite(new String[] {
        "                ",
        "                ",
        "      XX        ",
        "                ",
        "  XX  XX  XX    ",
        "                ",
        "    XX  XX      ",
        "                ",
        "                ",
        "    XXXXXXXXXX  ",
        "  XXXXXXXXXXXX  ",
        "XXXXXXXXXXXXXX  ",
        "XXXXXXXXXXXXXX  ",
        "XXXXXXXXXXXX    ",
        "XXXXXXXXXX      ",
        "                ",
      }, new ConsoleColor[] {
        ConsoleColor.White,
        ConsoleColor.White,
        ConsoleColor.White,
        ConsoleColor.White,
        ConsoleColor.White,
        ConsoleColor.White,
        ConsoleColor.White,
        ConsoleColor.White,
        ConsoleColor.White,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
      }),
      new Sprite(new String[] {
        "                ",
        "      XX        ",
        "                ",
        "XX    XX    XX  ",
        "                ",
        "  XX  XX  XX    ",
        "                ",
        "      XX        ",
        "                ",
        "    XXXXXXXXXX  ",
        "  XXXXXXXXXXXX  ",
        "XXXXXXXXXXXXXX  ",
        "XXXXXXXXXXXXXX  ",
        "XXXXXXXXXXXX    ",
        "XXXXXXXXXX      ",
        "                ",
      }, new ConsoleColor[] {
        ConsoleColor.White,
        ConsoleColor.White,
        ConsoleColor.White,
        ConsoleColor.White,
        ConsoleColor.White,
        ConsoleColor.White,
        ConsoleColor.White,
        ConsoleColor.White,
        ConsoleColor.White,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
      }),
    };
    public Sprite[] silverSprites = new Sprite[] {
      new Sprite(new String[] {
        "                ",
        "                ",
        "      XX        ",
        "                ",
        "  XX  XX  XX    ",
        "                ",
        "    XX  XX      ",
        "                ",
        "                ",
        "    XXXXXXXXXX  ",
        "  XXXXXXXXXXXX  ",
        "XXXXXXXXXXXXXX  ",
        "XXXXXXXXXXXXXX  ",
        "XXXXXXXXXXXX    ",
        "XXXXXXXXXX      ",
        "                ",
      }, new ConsoleColor[] {
        ConsoleColor.White,
        ConsoleColor.White,
        ConsoleColor.White,
        ConsoleColor.White,
        ConsoleColor.White,
        ConsoleColor.White,
        ConsoleColor.White,
        ConsoleColor.White,
        ConsoleColor.White,
        ConsoleColor.Gray,
        ConsoleColor.Gray,
        ConsoleColor.Gray,
        ConsoleColor.Gray,
        ConsoleColor.Gray,
        ConsoleColor.Gray,
        ConsoleColor.Gray,
      }),
      new Sprite(new String[] {
        "                ",
        "      XX        ",
        "                ",
        "XX    XX    XX  ",
        "                ",
        "  XX  XX  XX    ",
        "                ",
        "      XX        ",
        "                ",
        "    XXXXXXXXXX  ",
        "  XXXXXXXXXXXX  ",
        "XXXXXXXXXXXXXX  ",
        "XXXXXXXXXXXXXX  ",
        "XXXXXXXXXXXX    ",
        "XXXXXXXXXX      ",
        "                ",
      }, new ConsoleColor[] {
        ConsoleColor.White,
        ConsoleColor.White,
        ConsoleColor.White,
        ConsoleColor.White,
        ConsoleColor.White,
        ConsoleColor.White,
        ConsoleColor.White,
        ConsoleColor.White,
        ConsoleColor.White,
        ConsoleColor.Gray,
        ConsoleColor.Gray,
        ConsoleColor.Gray,
        ConsoleColor.Gray,
        ConsoleColor.Gray,
        ConsoleColor.Gray,
        ConsoleColor.Gray,
      }),
    };
    public Sprite wallSprite = new Sprite(new String[] {  
      "BBBBBBBBBBBBBMMBBBBBBBBBBBBB",
      "GGGGGGGGGGGGGGGGGGGGGGGGGGGG",      
      "BBBBBMMBBBBBBBBBBBBBBMMBBBBB",
      "BBBBBMMBBBBBBBBBBBBBBMMBBBBB",
      "BBBBBMMBBBBBBBBBBBBBBMMBBBBB",
      "GGGGGGGGGGGGGGGGGGGGGGGGGGGG",
      "BBBBBBBBBBBBBMMBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBMMBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBMMBBBBBBBBBBBBB",
      "GGGGGGGGGGGGGGGGGGGGGGGGGGGG",
      "BBBBBMMBBBBBBBBBBBBBBMMBBBBB",
      "BBBBBMMBBBBBBBBBBBBBBMMBBBBB",
      "BBBBBMMBBBBBBBBBBBBBBMMBBBBB",
      "GGGGGGGGGGGGGGGGGGGGGGGGGGGG",
      "BBBBBBBBBBBBBMMBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBMMBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBMMBBBBBBBBBBBBB",
      "GGGGGGGGGGGGGGGGGGGGGGGGGGGG",
      "BBBBBMMBBBBBBBBBBBBBBMMBBBBB",
      "BBBBBMMBBBBBBBBBBBBBBMMBBBBB",
      "BBBBBMMBBBBBBBBBBBBBBMMBBBBB",
      "GGGGGGGGGGGGGGGGGGGGGGGGGGGG",
      "BBBBBBBBBBBBBMMBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBMMBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBMMBBBBBBBBBBBBB",
      "GGGGGGGGGGGGGGGGGGGGGGGGGGGG",
      "BBBBBMMBBBBBBBBBBBBBBMMBBBBB",
      "BBBBBMMBBBBBBBBBBBBBBMMBBBBB",
      "BBBBBMMBBBBBBBBBBBBBBMMBBBBB",
      "GGGGGGGGGGGGGGGGGGGGGGGGGGGG",
      "BBBBBBBBBBBBBMMBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBMMBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBMMBBBBBBBBBBBBB",
      "GGGGGGGGGGGGGGGGGGGGGGGGGGGG",
      "BBBBBMMBBBBBBBBBBBBBBMMBBBBB",
      "BBBBBMMBBBBBBBBBBBBBBMMBBBBB",
      "BBBBBMMBBBBBBBBBBBBBBMMBBBBB",
      "GGGGGGGGGGGGGGGGGGGGGGGGGGGG",
      "BBBBBBBBBBBBBMMBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBMMBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBMMBBBBBBBBBBBBB",
      "GGGGGGGGGGGGGGGGGGGGGGGGGGGG",
      "BBBBBMMBBBBBBBBBBBBBBMMBBBBB",
      "BBBBBMMBBBBBBBBBBBBBBMMBBBBB",
      "BBBBBMMBBBBBBBBBBBBBBMMBBBBB",
      "GGGGGGGGGGGGGGGGGGGGGGGGGGGG",
      "BBBBBBBBBBBBBMMBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBMMBBBBBBBBBBBBB",
      "BBBBBBBBBBBBBMMBBBBBBBBBBBBB",
      "GGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    }, new char[] { 'B', 'M', 'G' }, 
      new ConsoleColor[] {
      ConsoleColor.DarkRed,
      ConsoleColor.Black,
      ConsoleColor.Gray,
    });
    public Sprite[] scorpionSprites = new Sprite[] {
      new Sprite(new String[] {
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "    XXXXXXXXXXXX                ",
        "XXXXXXXX    XXXXXXXX            ",
        "XXXX            XXXX            ",
        "XXXX        RXXX        RRRR    ",
        "XXXXXXXX            XXXX        ",
        "XXXXXXXXXXXXXXXXXXXX    RRRR    ",
        "    XXXXXXXXXXXXXXXX            ",
        "        XXXXXXXXXXXXXXXX        ",
        "        XXXXXXXX        XXXXRRRR",
        "    CCCC        CCCC        RRRR",
      }, new char[] { 'X', 'R', 'C' }, 
      new ConsoleColor[] {
        ConsoleColor.DarkRed,
        ConsoleColor.Red,
        ConsoleColor.DarkRed
      }),
      new Sprite(new String[] {
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "    XXXXXXXXXXXX                ",
        "XXXXXXXX    XXXXXXXX            ",
        "XXXX            XXXX            ",
        "XXXX        RXXX                ",
        "XXXX                    RRRR    ",
        "XXXXXXXX            XXXXRRRR    ",
        "XXXXXXXXXXXXXXXXXXXX            ",
        "    XXXXXXXXXXXXXXXX            ",
        "        XXXXXXXXXXXXXXXX    RRRR",
        "        XXXXXXXX        XXXX    ",
        "CCCC                CCCC    RRRR",
      }, new char[] { 'X', 'R', 'C' }, 
      new ConsoleColor[] {
        ConsoleColor.DarkRed,
        ConsoleColor.Red,
        ConsoleColor.DarkRed,
      }),
    };
    public Sprite moneySprite = new Sprite(new String[] {
      "                ",
      "    XXXX  XXXX  ",
      "      XXXXXX    ",
      "        YY      ",
      "      XXXXXX    ",
      "    XXXXZZXXXX  ",
      "    XXXXZZXXXX  ",
      "  XXXXZZZZZZXXXX",
      "  XXXXZZXXXXXXXX",
      "  XXXXZZZZZZXXXX",
      "  XXXXXXXXZZXXXX",
      "  XXXXZZZZZZXXXX",
      "  XXXXXXZZXXXXXX",
      "  XXXXXXZZXXXXXX",
      "    XXXXXXXXXX  ",
      "                ",
    }, new char[] { 'X', 'Y', 'Z' },
       new ConsoleColor[] { ConsoleColor.DarkCyan, ConsoleColor.Gray, ConsoleColor.Yellow }
    );
    public Sprite[] crocodileSprites = new Sprite[] {
      new Sprite(new String[] {
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                                ",
        "                    XXXX        ",
        "                    XBXBXXXX    ",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        " W  WWW  W  WWW  W  WWW  XXXXXXX",
        "WWW  W  WWW  W  WWW  W  XXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      },
        new char[] { 'X', 'W', 'B' }, 
        new ConsoleColor[] { ConsoleColor.Green, ConsoleColor.White, ConsoleColor.Black }),
      new Sprite(new String[] {
        "                                ",
        "                                ",
        "XXXX                            ",
        "XXXXXXXXXXXX         XXXXXX     ",
        "    WWW XXXXXXXXXXXXXBXBXXXXX   ",
        "    W       WWW XXXXXXXXXXXXXX  ",
        "            W       WWWXXXXXXXXX",
        "                    W    XXXXXXX",
        " W       W       W       XXXXXXX",
        "WWW     WWW     WWW     XXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      }, 
        new char[] { 'X', 'W', 'B' }, 
        new ConsoleColor[] { ConsoleColor.Green, ConsoleColor.White, ConsoleColor.Black }),
    };
    public Sprite crocodileMaskSprite = new Sprite(new String[] {
        " W       W       W       XXXXXXX",
        "WWW     WWW     WWW     XXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
        "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
      },
      new char[] { 'X', 'W', 'B', 'G' },
      new ConsoleColor[] { ConsoleColor.Green, ConsoleColor.White, ConsoleColor.Blue, ConsoleColor.DarkGray }
    );
    public Sprite[] cobraSprites = new Sprite[] {
      new Sprite(new String[] {
        "                ",
        "XX              ",
        "    XXXX        ",
        "    XXXXXX      ",
        "        XX      ",
        "        XXXX    ",
        "        XXXX    ",
        "        XX      ",
        "      XX        ",
        "  XXXX          ",
        "XXXXXXXXXX  XX  ",
        "XXXXXXXXXX  XX  ",
        "XXXXXXXXXX    XX",
        "XXXXXXXXXX    XX",
        "XXXXXXXXXXXXXX  ",
        "                ",
      }, new ConsoleColor[] {
        ConsoleColor.Red,
        ConsoleColor.Red,
        ConsoleColor.DarkMagenta,
        ConsoleColor.DarkMagenta,
        ConsoleColor.DarkMagenta,
        ConsoleColor.DarkMagenta,
        ConsoleColor.DarkMagenta,
        ConsoleColor.DarkMagenta,
        ConsoleColor.DarkMagenta,
        ConsoleColor.DarkMagenta,
        ConsoleColor.DarkMagenta,
        ConsoleColor.Magenta,
        ConsoleColor.DarkMagenta,
        ConsoleColor.Magenta,
        ConsoleColor.DarkMagenta,
        ConsoleColor.DarkMagenta,
      }),
      new Sprite(new String[] {
        "                ",
        "  XX            ",
        "    XXXX        ",
        "    XXXXXX      ",
        "        XX      ",
        "        XXXX    ",
        "        XXXX    ",
        "        XX      ",
        "      XX        ",
        "  XXXX          ",
        "XXXXXXXXXX    XX",
        "XXXXXXXXXX    XX",
        "XXXXXXXXXX    XX",
        "XXXXXXXXXX    XX",
        "XXXXXXXXXXXXXX  ",
        "                ",
      }, new ConsoleColor[] {
        ConsoleColor.Red,
        ConsoleColor.Red,
        ConsoleColor.DarkMagenta,
        ConsoleColor.DarkMagenta,
        ConsoleColor.DarkMagenta,
        ConsoleColor.DarkMagenta,
        ConsoleColor.DarkMagenta,
        ConsoleColor.DarkMagenta,
        ConsoleColor.DarkMagenta,
        ConsoleColor.DarkMagenta,
        ConsoleColor.DarkMagenta,
        ConsoleColor.Magenta,
        ConsoleColor.DarkMagenta,
        ConsoleColor.Magenta,
        ConsoleColor.DarkMagenta,
        ConsoleColor.DarkMagenta,
      }),
    };
    public Sprite[] fireSprites = new Sprite[] {
      new Sprite(new String[] {
        "        XX      ",
        "        XX      ",
        "        XXXX    ",
        "        XXXX    ",
        "      XXXXXX    ",
        "      XXXXXX    ",
        "      XXXXXXXX  ",
        "    XXXXXXXXXX  ",
        "    XXXXXXXXXX  ",
        "    XXXXXXXX    ",
        "      XXXX      ",
        "    XXXXXXXX    ",
        "  XXXXXXXXXXXX  ",
        "XXXXXX    XXXXXX",
        "XXXX        XXXX",
        "                ",
      }, new ConsoleColor[] {
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.DarkRed,
        ConsoleColor.DarkRed,
        ConsoleColor.DarkRed,
        ConsoleColor.DarkRed,
        ConsoleColor.DarkRed,
      }),
      new Sprite(new String[] {
        "      XX        ",
        "      XX        ",
        "    XXXX        ",
        "    XXXX        ",
        "    XXXXXX      ",
        "    XXXXXX      ",
        "  XXXXXXXX      ",
        "  XXXXXXXXXX    ",
        "  XXXXXXXXXX    ",
        "    XXXXXXXX    ",
        "      XXXX      ",
        "    XXXXXXXX    ",
        "  XXXXXXXXXXXX  ",
        "XXXXXX    XXXXXX",
        "XXXX        XXXX",
        "                ",
      }, new ConsoleColor[] {
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.DarkRed,
        ConsoleColor.DarkRed,
        ConsoleColor.DarkRed,
        ConsoleColor.DarkRed,
        ConsoleColor.DarkRed,
      }),
    };
    public Sprite[] logSprites = new Sprite[] {
      new Sprite(new String[] {
        "                ",
        "      XXXX      ",
        "    XXXXXXXX    ",
        "  XXXXFFXXXXXX  ",
        "  XXXXXXXXFFXX  ",
        "  XXXXXXXXXXXX  ",
        "  XXXXFFXXXXXX  ",
        "  XXXXXXXXFFXX  ",
        "  XXXXXXXXXXXX  ",
        "  XXXXFFFFXXXX  ",
        "  XXFFXXXXFFXX  ",
        "  XXFFXXXXFFXX  ",
        "  XXFFXXXXFFXX  ",
        "    XXFFFFXX    ",
        "      XXXX      ",
        "                ",
      }, 
        new char[] { 'X', 'F' },
        new ConsoleColor[] { ConsoleColor.DarkRed, ConsoleColor.Black }),
      new Sprite(new String[] {
        "                ",
        "      XXXX      ",
        "    XXXXXXXX    ",
        "  XXXXXXFFXXXX  ",
        "  XXFFXXXXXXXX  ",
        "  XXXXXXXXXXXX  ",
        "  XXXXXXFFXXXX  ",
        "  XXFFXXXXXXXX  ",
        "  XXXXXXXXXXXX  ",
        "  XXXXFFFFXXXX  ",
        "  XXFFXXXXFFXX  ",
        "  XXFFXXXXFFXX  ",
        "  XXFFXXXXFFXX  ",
        "    XXFFFFXX    ",
        "      XXXX      ",
        "                ", 
      },
        new char[] { 'X', 'F' },
        new ConsoleColor[] { ConsoleColor.DarkRed, ConsoleColor.Black }),
    };
    public Sprite harryClimbingSprite = new Sprite(new String[] {
      "      XXXX      ",
      "      XXXX      ",
      "      XXXX      ",
      "  XX            ",
      "  XX  XXXX      ",
      "  XXXXXXXX      ",
      "    XXXXXXXX    ",
      "      XXXXXX    ",
      "      XXXXXX    ",
      "      XXXX      ",
      "    XXXXXX      ",
      "  XXXXXXXX      ",
      "  XXXX  XX      ",
      "  XX    XX      ",
      "  XXXX  XX      ",
      "    XX  XX      ",
      "    XX  XX      ",
      "  XXXX  XX      ",
      "        XX      ",
      "        XX      ",
      "        XX      ",
      "        XXXX    ",
    }, new ConsoleColor[] {
      ConsoleColor.DarkYellow,
      ConsoleColor.Yellow,
      ConsoleColor.Yellow,
      ConsoleColor.Yellow,
      ConsoleColor.Green,
      ConsoleColor.Green,
      ConsoleColor.Green,
      ConsoleColor.Green,
      ConsoleColor.Green,
      ConsoleColor.Green,
      ConsoleColor.DarkGreen,
      ConsoleColor.DarkGreen,
      ConsoleColor.DarkGreen,
      ConsoleColor.DarkGreen,
      ConsoleColor.DarkGreen,
      ConsoleColor.DarkGreen,
      ConsoleColor.DarkGreen,
      ConsoleColor.DarkGreen,
      ConsoleColor.DarkGreen,
      ConsoleColor.DarkGreen,
      ConsoleColor.DarkGreen,
      ConsoleColor.DarkGreen,
    });
    public Sprite harrySwingingSprite = new Sprite(new String[] {
      "                ",
      "XXXX            ",
      "XXXX  XX        ",
      "XXXX  XX        ",
      "XX    XX        ",
      "XXXX  XX        ",
      "XXXXXXXX        ",
      "XXXX            ",
      "XXXX            ",
      "XXXX            ",
      "XXXX            ",
      "XXXX            ",
      "XXXX  XXXXXX    ",
      "XXXXXXXX  XXXX  ",
      "XXXXXXXX    XX  ",
      "  XXXX      XXXX",
      "                ",
      "                ",
      "                ",
      "                ",
      "                ",
      "                ",
    }, new ConsoleColor[] {
      ConsoleColor.DarkYellow,
      ConsoleColor.DarkYellow,
      ConsoleColor.Yellow,
      ConsoleColor.Yellow,
      ConsoleColor.Yellow,
      ConsoleColor.Green,
      ConsoleColor.Green,
      ConsoleColor.Green,
      ConsoleColor.Green,
      ConsoleColor.Green,
      ConsoleColor.Green,
      ConsoleColor.Green,
      ConsoleColor.DarkGreen,
      ConsoleColor.DarkGreen,
      ConsoleColor.DarkGreen,
      ConsoleColor.DarkGreen,
      ConsoleColor.DarkGreen,
      ConsoleColor.DarkGreen,
      ConsoleColor.DarkGreen,
      ConsoleColor.DarkGreen,
      ConsoleColor.DarkGreen,
      ConsoleColor.DarkGreen,
    });
    public Sprite harryStandingSprite = new Sprite(new String[] {
      "                ",
      "      XXXX      ",
      "      XXXX      ",
      "      XXXX      ",
      "      XX        ",
      "      XXXX      ",
      "      XXXX      ",
      "      XXXX  XX  ",
      "      XXXXXXXX  ",
      "      XXXXXX    ",
      "      XXXX      ",
      "      XXXX      ",
      "      XXXX      ",
      "      XXXX      ",
      "      XXXX      ",
      "      XXXX      ",
      "      XXXX      ",
      "      XXXX      ",
      "      XXXX      ",
      "      XXXXXX    ",
      "      XX        ",
      "      XXXX      ",
    }, new ConsoleColor[] {
      ConsoleColor.DarkYellow,
      ConsoleColor.DarkYellow,
      ConsoleColor.Yellow,
      ConsoleColor.Yellow,
      ConsoleColor.Yellow,
      ConsoleColor.Green,
      ConsoleColor.Green,
      ConsoleColor.Green,
      ConsoleColor.Green,
      ConsoleColor.Green,
      ConsoleColor.Green,
      ConsoleColor.Green,
      ConsoleColor.DarkGreen,
      ConsoleColor.DarkGreen,
      ConsoleColor.DarkGreen,
      ConsoleColor.DarkGreen,
      ConsoleColor.DarkGreen,
      ConsoleColor.DarkGreen,
      ConsoleColor.DarkGreen,
      ConsoleColor.DarkGreen,
      ConsoleColor.DarkGreen,
      ConsoleColor.DarkGreen,
    });
    public Sprite[] harryRunningSprites = new Sprite[] {
      new Sprite(new String[] {
        "                ",
        "      XXXX      ",
        "      XXXX      ",
        "      XXXX      ",
        "      XX        ",
        "      XXXX      ",
        "      XXXX      ",
        "    XXXXXX      ",
        "    XXXXXX  XX  ",
        "    XXXXXXXXXX  ",
        "    XXXXXXXX    ",
        "      XXXX      ",
        "      XXXX      ",
        "      XXXX      ",
        "      XXXXXX    ",
        "      XXXXXX    ",
        "      XX  XX    ",
        "  XXXXXX  XX    ",
        "  XX      XX    ",
        "  XX        XXXX",
        "            XX  ",
        "                ",
      }, new ConsoleColor[] {
        ConsoleColor.DarkYellow,
        ConsoleColor.DarkYellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Green,
        ConsoleColor.Green,
        ConsoleColor.Green,
        ConsoleColor.Green,
        ConsoleColor.Green,
        ConsoleColor.Green,
        ConsoleColor.Green,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
      }),
      new Sprite(new String[] {
        "                ",
        "      XXXX      ",
        "      XXXX      ",
        "      XXXX      ",
        "      XX        ",
        "      XXXX      ",
        "      XXXX      ",
        "      XXXX      ",
        "      XXXX      ",
        "      XXXX      ",
        "      XXXXXX    ",
        "      XXXXXX    ",
        "      XXXX      ",
        "      XXXX      ",
        "      XXXXXX    ",
        "        XXXXXX  ",
        "        XX  XX  ",
        "    XXXXXXXXXX  ",
        "    XX  XX      ",
        "    XX  XX      ",
        "        XX      ",
        "        XXXX    ",
      }, new ConsoleColor[] {
        ConsoleColor.DarkYellow,
        ConsoleColor.DarkYellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Green,
        ConsoleColor.Green,
        ConsoleColor.Green,
        ConsoleColor.Green,
        ConsoleColor.Green,
        ConsoleColor.Green,
        ConsoleColor.Green,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
      }),

      new Sprite(new String[] {
        "                ",
        "      XXXX      ",
        "      XXXX      ",
        "      XXXX      ",
        "      XX        ",
        "      XXXX      ",
        "      XXXX      ",
        "      XXXX      ",
        "      XXXX      ",
        "      XXXXXX    ",
        "      XXXXXX    ",
        "      XXXX      ",
        "      XXXX      ",
        "      XXXXXX    ",
        "      XXXXXXXX  ",
        "      XX  XXXX  ",
        "    XXXX    XX  ",
        "    XXXX  XX    ",
        "    XX    XX    ",
        "    XX      XX  ",
        "    XX          ",
        "      XX        ",
      }, new ConsoleColor[] {
        ConsoleColor.DarkYellow,
        ConsoleColor.DarkYellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Green,
        ConsoleColor.Green,
        ConsoleColor.Green,
        ConsoleColor.Green,
        ConsoleColor.Green,
        ConsoleColor.Green,
        ConsoleColor.Green,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
      }),
      new Sprite(new String[] {
        "                ",
        "      XXXX      ",
        "      XXXX      ",
        "      XXXX      ",
        "      XX        ",
        "      XXXX      ",
        "      XXXX      ",
        "    XXXXXX      ",
        "    XXXXXX  XX  ",
        "    XXXXXXXXXX  ",
        "    XXXXXXXX    ",
        "      XXXX      ",
        "      XXXX      ",
        "      XXXXXX    ",
        "    XXXXXXXXXX  ",
        "    XXXX  XXXX  ",
        "  XXXX      XX  ",
        "  XXXX      XX  ",
        "XXXX        XXXX",
        "XX              ",
        "XX              ",
        "                ",
      }, new ConsoleColor[] {
        ConsoleColor.DarkYellow,
        ConsoleColor.DarkYellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Green,
        ConsoleColor.Green,
        ConsoleColor.Green,
        ConsoleColor.Green,
        ConsoleColor.Green,
        ConsoleColor.Green,
        ConsoleColor.Green,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
      }),
      new Sprite(new String[] {
        "                ",
        "      XXXX      ",
        "      XXXX      ",
        "      XXXX      ",
        "      XX        ",
        "      XXXX      ",
        "      XXXX  XX  ",
        "    XXXXXXXXXX  ",
        "  XXXXXXXXXX    ",
        "  XX  XXXX      ",
        "  XX  XXXX      ",
        "      XXXX      ",
        "      XXXXXX    ",
        "      XXXXXXXX  ",
        "XXXX  XXXX  XX  ",
        "  XXXXXX    XX  ",
        "    XXXX    XXXX",
        "                ",
        "                ",
        "                ",
        "                ",
        "                ",
      }, new ConsoleColor[] {
        ConsoleColor.DarkYellow,
        ConsoleColor.DarkYellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Yellow,
        ConsoleColor.Green,
        ConsoleColor.Green,
        ConsoleColor.Green,
        ConsoleColor.Green,
        ConsoleColor.Green,
        ConsoleColor.Green,
        ConsoleColor.Green,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
        ConsoleColor.DarkGreen,
      })
    };
    public Sprite ladderHoleSprite = new Sprite(new String[] {
      "        XXXXXXXXXXXXXXXX        ",
      "    XXXXXXBXXXXXXXXXXBXXXXXX    ",
      " XXXXXXXXXBBBBBBBBBBBBXXXXXXXXX ",
      "XXXXXXXXXXBXXXXXXXXXXBXXXXXXXXXX",
      "XXXXXXXXXXBBBBBBBBBBBBXXXXXXXXXX",
      " XXXXXXXXXBXXXXXXXXXXBXXXXXXXXX ",
      "    XXXXXXBBBBBBBBBBBBXXXXXX    ",
      "        XXBXXXXXXXXXXBXX        ",    
    }, new char[] { 'X', 'B' }, new ConsoleColor[] { ConsoleColor.Black, ConsoleColor.DarkRed });
    public Sprite ladderHoleDropSprite = new Sprite(new String[] {
      "        XXXXXXXXXXXXXXXX        ",
      "    XXXXXBBXXXXXXXXXXBBXXXXX    ",
      " XXXXXXXXXBBBBBBBBBBBBXXXXXXXXX ",
      "XXXXXXXXXXBXXXXXXXXXXBXXXXXXXXXX",
      "XXXXXXXXXXBBBBBBBBBBBBXXXXXXXXXX",
      " XXXXXXXXXBXXXXXXXXXXBXXXXXXXXX ",
      "    XXXXXXBBBBBBBBBBBBXXXXXX    ",
      "        XXBXXXXXXXXXXBXX        ",    
    }, new char[] { 'X', 'B' }, new ConsoleColor[] { ConsoleColor.Black, ConsoleColor.DarkRed });
    public Sprite ladderHoleBacktrackSprite = new Sprite(new String[] {
      "        XXXXXXXXXXXXXXXX        ",
      "    XXXXXXBXXXXXXXXXXBBXXXXX    ",
      " XXXXXXXXXBBBBBBBBBBBBXXXXXXXXX ",
      "XXXXXXXXXXBXXXXXXXXXXBXXXXXXXXXX",
      "XXXXXXXXXXBBBBBBBBBBBBXXXXXXXXXX",
      " XXXXXXXXXBXXXXXXXXXXBXXXXXXXXX ",
      "    XXXXXXBBBBBBBBBBBBXXXXXX    ",
      "        XXBXXXXXXXXXXBXX        ",    
    }, new char[] { 'X', 'B' }, new ConsoleColor[] { ConsoleColor.Black, ConsoleColor.DarkRed });
    public Sprite ladderSprite = new Sprite(new string[] {
      "X          X",
      "XXXXXXXXXXXX",
      "X          X",
      "XXXXXXXXXXXX",
      "X          X",
      "XXXXXXXXXXXX",
      "X          X",
      "XXXXXXXXXXXX",
      "X          X",
      "XXXXXXXXXXXX",
      "X          X",
      "XXXXXXXXXXXX",
      "X          X",
      "XXXXXXXXXXXX",
      "X          X",
      "XXXXXXXXXXXX",
      "X          X",
      "XXXXXXXXXXXX",
      "X          X",
      "XXXXXXXXXXXX",
      "X          X",
      "XXXXXXXXXXXX",
      "X          X",
      "XXXXXXXXXXXX",
      "X          X",
      "XXXXXXXXXXXX",
      "X          X",
      "XXXXXXXXXXXX",
      "X          X",
      "XXXXXXXXXXXX",
      "X          X",
      "XXXXXXXXXXXX",
      "X          X",
      "XXXXXXXXXXXX",
      "X          X",
      "XXXXXXXXXXXX",
      "X          X",
      "XXXXXXXXXXXX",
      "X          X",
      "XXXXXXXXXXXX",
      "X          X",
      "XXXXXXXXXXXX",
      "X          X",
      "XXXXXXXXXXXX",
      "X          X",
    }, ConsoleColor.DarkRed);
    public Sprite ladderHoleMaskSprite = new Sprite(new String[] {
      "X                              X",
      "XXXX                        XXXX",
      "XXXXXXXX                XXXXXXXX",    
      "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    }, ConsoleColor.DarkGray);
    public Sprite tunnelHoleSprite = new Sprite(new String[] {
      "        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        ",
      "    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ",
      " XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ",
      "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      " XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ",
      "    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ",
      "        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        ",    
    }, ConsoleColor.Black);
    public Sprite tunnelHoleMaskSprite = new Sprite(new String[] {
      "X                                              X",
      "XXXX                                        XXXX",
      "XXXXXXXX                                XXXXXXXX",
      "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    }, ConsoleColor.DarkGray);
    public Sprite tarPitSprite = new Sprite(new String[] {
      "                           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                           ",
      "            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX            ",
      "   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
      "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
      "            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX            ",
      "                           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                           ",    
    }, ConsoleColor.Black);
    public Sprite tarPitMaskSprite = new Sprite(new String[] {
      "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "YYYXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXYYY",
      "YYYYYYYYYYYYXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXYYYYYYYYYYYY",
      "YYYYYYYYYYYYYYYYYYYYYYYYYYYXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXYYYYYYYYYYYYYYYYYYYYYYYYYYY",    
      "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY",    
      "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY",    
    }, new char[] { 'X', 'Y' }, new ConsoleColor[] { ConsoleColor.Black, ConsoleColor.DarkGray });
    public Sprite[] shiftingTarPitSprites = new Sprite[] {
      new Sprite(new String[] {
        "                                     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                     ",
        "                      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                      ",
        "   X         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX         X   ",
        "X         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX         X",
        "X         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX         X",
        "   X         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX         X   ",
        "                      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                      ",
        "                                     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                     ",    
      }, ConsoleColor.Black),
      new Sprite(new String[] {
        "                                                                                                                                                                                                                ",
        "                                               XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                               ",
        "   X                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                            X   ",
        "X                      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                      X",
        "X                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                   X",
        "   X                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                   X   ",
        "                                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                ",
        "                                               XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                               ",    
      }, ConsoleColor.Black),
      new Sprite(new String[] {
        "                                                                                                                                                                                                                ",
        "                                                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                            ",
        "   X                                         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                         X   ",
        "X                                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                   X",
        "X                                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                   X",
        "   X                                         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                         X   ",
        "                                                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                            ",    
        "                                                                                                                                                                                                                ",
      }, ConsoleColor.Black),
      new Sprite(new String[] {
        "                                                                                                                                                                                                                ",
        "                                                                                                                                                                                                                ",
        "   X                                                                       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                                       X   ",
        "X                                                           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                           X",
        "X                                                  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                  X",
        "   X                                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                        X   ",
        "                                                                           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                                           ",    
        "                                                                                                                                                                                                                ",
      }, ConsoleColor.Black),
      new Sprite(new String[] {
        "                                                                                                                                                                                                                ",
        "                                                                                                                                                                                                                ",
        "   X                                                                                         XXXXXXXXXXXXXXXXXXXXXX                                                                                         X   ",
        "X                                                                             XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                                             X",
        "X                                                                             XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                                             X",
        "   X                                                                                         XXXXXXXXXXXXXXXXXXXXXX                                                                                         X   ",    
        "                                                                                                                                                                                                                ",
        "                                                                                                                                                                                                                ",
      }, ConsoleColor.Black),
      new Sprite(new String[] {
        "                                                                                                                                                                                                                ",
        "                                                                                                                                                                                                                ",
        "   X                                                                                                                                                                                                        X   ",
        "X                                                                                           XXXXXXXXXXXXXXXXXXXXXXX                                                                                            X",
        "X                                                                                           XXXXXXXXXXXXXXXXXXXXXXX                                                                                            X",
        "   X                                                                                                                                                                                                        X   ",    
        "                                                                                                                                                                                                                ",
        "                                                                                                                                                                                                                ",
      }, ConsoleColor.Black),
      new Sprite(new String[] {
        "                                                                                                                                                                                                                ",
        "                                                                                                                                                                                                                ",
        "   X                                                                                                                                                                                                        X   ",
        "X                                                                                                                                                                                                              X",
        "X                                                                                                                                                                                                              X",
        "   X                                                                                                                                                                                                        X   ",    
        "                                                                                                                                                                                                                ",
        "                                                                                                                                                                                                                ",
      }, ConsoleColor.Black),
    };
    public Sprite quickSandSprite = new Sprite(new String[] {
      "                           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                           ",
      "            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX            ",
      "   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
      "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
      "            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX            ",
      "                           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                           ",    
    }, ConsoleColor.Blue);
    public Sprite quickSandMaskSprite = new Sprite(new String[] {
      "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "YYYXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXYYY",
      "YYYYYYYYYYYYXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXYYYYYYYYYYYY",
      "YYYYYYYYYYYYYYYYYYYYYYYYYYYXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXYYYYYYYYYYYYYYYYYYYYYYYYYYY",    
      "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY",    
      "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY",    
    }, new char[] { 'X', 'Y' }, new ConsoleColor[] { ConsoleColor.Blue, ConsoleColor.DarkGray });

    public Sprite[] shiftingQuickSandSprites = new Sprite[] {
      new Sprite(new String[] {
        "                                     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                     ",
        "                      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                      ",
        "   X         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX         X   ",
        "X         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX         X",
        "X         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX         X",
        "   X         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX         X   ",
        "                      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                      ",
        "                                     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                     ",    
      }, ConsoleColor.Blue),
      new Sprite(new String[] {
        "                                                                                                                                                                                                                ",
        "                                               XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                               ",
        "   X                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                            X   ",
        "X                      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                      X",
        "X                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                   X",
        "   X                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                   X   ",
        "                                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                ",
        "                                               XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                               ",    
      }, ConsoleColor.Blue),
      new Sprite(new String[] {
        "                                                                                                                                                                                                                ",
        "                                                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                            ",
        "   X                                         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                         X   ",
        "X                                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                   X",
        "X                                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                   X",
        "   X                                         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                         X   ",
        "                                                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                            ",    
        "                                                                                                                                                                                                                ",
      }, ConsoleColor.Blue),
      new Sprite(new String[] {
        "                                                                                                                                                                                                                ",
        "                                                                                                                                                                                                                ",
        "   X                                                                       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                                       X   ",
        "X                                                           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                           X",
        "X                                                  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                  X",
        "   X                                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                        X   ",
        "                                                                           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                                           ",    
        "                                                                                                                                                                                                                ",
      }, ConsoleColor.Blue),
      new Sprite(new String[] {
        "                                                                                                                                                                                                                ",
        "                                                                                                                                                                                                                ",
        "   X                                                                                         XXXXXXXXXXXXXXXXXXXXXX                                                                                         X   ",
        "X                                                                             XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                                             X",
        "X                                                                             XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                                             X",
        "   X                                                                                         XXXXXXXXXXXXXXXXXXXXXX                                                                                         X   ",    
        "                                                                                                                                                                                                                ",
        "                                                                                                                                                                                                                ",
      }, ConsoleColor.Blue),
      new Sprite(new String[] {
        "                                                                                                                                                                                                                ",
        "                                                                                                                                                                                                                ",
        "   X                                                                                                                                                                                                        X   ",
        "X                                                                                           XXXXXXXXXXXXXXXXXXXXXXX                                                                                            X",
        "X                                                                                           XXXXXXXXXXXXXXXXXXXXXXX                                                                                            X",
        "   X                                                                                                                                                                                                        X   ",    
        "                                                                                                                                                                                                                ",
        "                                                                                                                                                                                                                ",
      }, ConsoleColor.Blue),
      new Sprite(new String[] {
        "                                                                                                                                                                                                                ",
        "                                                                                                                                                                                                                ",
        "   X                                                                                                                                                                                                        X   ",
        "X                                                                                                                                                                                                              X",
        "X                                                                                                                                                                                                              X",
        "   X                                                                                                                                                                                                        X   ",    
        "                                                                                                                                                                                                                ",
        "                                                                                                                                                                                                                ",
      }, ConsoleColor.Blue),
    };
  }
}
